/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DivideTrainTest extends javax.swing.JFrame {

    /**
     * Creates new form DivideTrainTest
     */
    public DivideTrainTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        openFileBtn = new javax.swing.JButton();
        percentTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputFileTxt = new javax.swing.JTextField();
        returnBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(28, 28, 28));

        jLabel4.setBackground(new java.awt.Color(240, 240, 240));
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(28, 28, 28));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CHUẨN BỊ DỮ LIỆU");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 28, 28));
        jLabel1.setText("Đọc dữ liệu (.arff):");

        openFileBtn.setBackground(new java.awt.Color(207, 207, 207));
        openFileBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        openFileBtn.setForeground(new java.awt.Color(28, 28, 28));
        openFileBtn.setText("Chọn file");
        openFileBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openFileBtn.setBorderPainted(false);
        openFileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openFileBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        openFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openFileBtnMouseClicked(evt);
            }
        });

        percentTxt.setBackground(new java.awt.Color(232, 232, 232));
        percentTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        percentTxt.setForeground(new java.awt.Color(28, 28, 28));
        percentTxt.setText("80");
        percentTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        percentTxt.setCaretColor(new java.awt.Color(0, 0, 0));
        percentTxt.setMargin(new java.awt.Insets(5, 20, 5, 20));
        percentTxt.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(28, 28, 28));
        jLabel2.setText("Tỉ lệ phần trăm (>50%):");

        inputFileTxt.setBackground(new java.awt.Color(232, 232, 232));
        inputFileTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        inputFileTxt.setForeground(new java.awt.Color(28, 28, 28));
        inputFileTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        inputFileTxt.setCaretColor(new java.awt.Color(0, 0, 0));
        inputFileTxt.setMargin(new java.awt.Insets(5, 20, 5, 20));
        inputFileTxt.setPreferredSize(new java.awt.Dimension(3, 30));
        inputFileTxt.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        returnBtn.setBackground(new java.awt.Color(207, 207, 207));
        returnBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        returnBtn.setForeground(new java.awt.Color(28, 28, 28));
        returnBtn.setText("Trở lại trang chủ");
        returnBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnBtn.setBorderPainted(false);
        returnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        returnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBtnMouseClicked(evt);
            }
        });

        startBtn.setBackground(new java.awt.Color(0, 100, 0));
        startBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("Thực hiện");
        startBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startBtn.setBorderPainted(false);
        startBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        startBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(205, 38, 38));
        resetBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset dữ liệu");
        resetBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetBtn.setBorderPainted(false);
        resetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resetBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        resetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(inputFileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(openFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(percentTxt)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFileTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(percentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBtnMouseClicked
        this.dispose();
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        homePage.setLocationRelativeTo(null);
    }//GEN-LAST:event_returnBtnMouseClicked

    private void resetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtnMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa dữ liệu đã nhập?", "Thông báo", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_OPTION) {
            inputFileTxt.setText("");
            percentTxt.setText("");
        } 
    }//GEN-LAST:event_resetBtnMouseClicked

    private void openFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openFileBtnMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int response = fileChooser.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION){
            File file = new File (fileChooser.getSelectedFile().getAbsolutePath());
            inputFileTxt.setText(file.toString());
        }
    }//GEN-LAST:event_openFileBtnMouseClicked
   
    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        int persent = 0;
        String fileTrain = "D:\\Doc\\Projects\\JavaApp\\diemthi_train.arff";
        String fileTest = "D:\\Doc\\Projects\\JavaApp\\diemthi_test.arff";
        if (inputFileTxt.getText().length()>0 && percentTxt.getText().length()>0){
            try {
                KnowledgeModel model = new KnowledgeModel(inputFileTxt.getText(),null,null);
                persent = Integer.parseInt(percentTxt.getText());
                if (persent > 50){
                    model.trainset = model.divideTrainTest(model.dataset, 100-persent, false);
                    model.testset = model.divideTrainTest(model.dataset, 100-persent, true);
                    
                    BufferedWriter outWriter_train = new BufferedWriter(new FileWriter(fileTrain));
                    outWriter_train.write(model.trainset.toString());
                    outWriter_train.newLine();
                    outWriter_train.flush();
                    outWriter_train.close();
                    
                    BufferedWriter outWriter_test = new BufferedWriter(new FileWriter(fileTest));
                    outWriter_test.write(model.testset.toString());
                    outWriter_test.newLine();
                    outWriter_test.flush();
                    outWriter_test.close();
                    JOptionPane.showMessageDialog(this, "Thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    
                }
                else {
                   JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng chọn tỉ lệ phần trăm lớn hơn 50%","Thông báo",JOptionPane.ERROR_MESSAGE); 
                }
            } catch (Exception ex) {
                Logger.getLogger(DivideTrainTest.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ dữ liệu trước khi thực hiện!","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_startBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DivideTrainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DivideTrainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DivideTrainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DivideTrainTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DivideTrainTest divideTrainTest = new DivideTrainTest();
                divideTrainTest.setVisible(true);
                divideTrainTest.setLocationRelativeTo(null);
                divideTrainTest.setTitle("Chuẩn bị dữ liệu");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputFileTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton openFileBtn;
    private javax.swing.JTextField percentTxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
