/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class KnnFrame extends javax.swing.JFrame {

    public knnModel model;
    public KnnFrame() throws Exception {
        initComponents();
        String k = knnTxt.getText();
        this.model = new knnModel("",
                "-K "+k+" -W 0 -A \"weka.core.neighboursearch.LinearNNSearch -A \\\"weka.core.EuclideanDistance -R first-last\\\"\"", null);
    }

/**
     * Creates new form KnnFrame
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        openFileBtn = new javax.swing.JButton();
        inputFileTxt = new javax.swing.JTextField();
        returnBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();
        evaluateBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        knnTxt = new javax.swing.JTextField();
        knnStartBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(28, 28, 28));

        jLabel4.setBackground(new java.awt.Color(240, 240, 240));
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(28, 28, 28));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PHÂN LỚP DỮ LIỆU");

        jLabel1.setBackground(new java.awt.Color(240, 240, 240));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 28, 28));
        jLabel1.setText("Đọc dữ liệu cần dự đoán (.arff):");

        openFileBtn.setBackground(new java.awt.Color(207, 207, 207));
        openFileBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        openFileBtn.setForeground(new java.awt.Color(28, 28, 28));
        openFileBtn.setText("Chọn file");
        openFileBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openFileBtn.setBorderPainted(false);
        openFileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openFileBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        openFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openFileBtnMouseClicked(evt);
            }
        });

        inputFileTxt.setBackground(new java.awt.Color(232, 232, 232));
        inputFileTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        inputFileTxt.setForeground(new java.awt.Color(28, 28, 28));
        inputFileTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        inputFileTxt.setCaretColor(new java.awt.Color(0, 0, 0));
        inputFileTxt.setMargin(new java.awt.Insets(5, 20, 5, 20));
        inputFileTxt.setPreferredSize(new java.awt.Dimension(3, 30));
        inputFileTxt.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        returnBtn.setBackground(new java.awt.Color(207, 207, 207));
        returnBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        returnBtn.setForeground(new java.awt.Color(28, 28, 28));
        returnBtn.setText("Trở lại trang chủ");
        returnBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnBtn.setBorderPainted(false);
        returnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        returnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBtnMouseClicked(evt);
            }
        });

        startBtn.setBackground(new java.awt.Color(0, 100, 0));
        startBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("Dự đoán nhãn lớp");
        startBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startBtn.setBorderPainted(false);
        startBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        startBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        evaluateBtn.setBackground(new java.awt.Color(207, 207, 207));
        evaluateBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        evaluateBtn.setForeground(new java.awt.Color(28, 28, 28));
        evaluateBtn.setText("Đánh giá");
        evaluateBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        evaluateBtn.setBorderPainted(false);
        evaluateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        evaluateBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        evaluateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluateBtnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(28, 28, 28));
        jLabel3.setText("KNN:");

        knnTxt.setBackground(new java.awt.Color(232, 232, 232));
        knnTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        knnTxt.setForeground(new java.awt.Color(28, 28, 28));
        knnTxt.setText("5");
        knnTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        knnTxt.setCaretColor(new java.awt.Color(0, 0, 0));
        knnTxt.setMargin(new java.awt.Insets(5, 20, 5, 20));
        knnTxt.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        knnStartBtn.setBackground(new java.awt.Color(0, 100, 0));
        knnStartBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        knnStartBtn.setForeground(new java.awt.Color(255, 255, 255));
        knnStartBtn.setText("Xây dựng mô hình");
        knnStartBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        knnStartBtn.setBorderPainted(false);
        knnStartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        knnStartBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        knnStartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                knnStartBtnMouseClicked(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(205, 38, 38));
        resetBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset dữ liệu");
        resetBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetBtn.setBorderPainted(false);
        resetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resetBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        resetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBtnMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(28, 28, 28));
        jLabel5.setText("Kết quả đánh giá:");

        resultTxt.setBackground(new java.awt.Color(232, 232, 232));
        resultTxt.setColumns(20);
        resultTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        resultTxt.setForeground(new java.awt.Color(28, 28, 28));
        resultTxt.setLineWrap(true);
        resultTxt.setRows(5);
        resultTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resultTxt.setCaretColor(new java.awt.Color(0, 0, 0));
        resultTxt.setMargin(new java.awt.Insets(10, 20, 10, 10));
        resultTxt.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(resultTxt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(inputFileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(startBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(knnTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(knnStartBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(evaluateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(knnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(knnStartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(evaluateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFileTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtnMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa dữ liệu đã nhập?", "Thông báo", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_OPTION) {
            knnTxt.setText("");
            inputFileTxt.setText("");
        } 
    }//GEN-LAST:event_resetBtnMouseClicked

    private void openFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openFileBtnMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int response = fileChooser.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION){
            File file = new File (fileChooser.getSelectedFile().getAbsolutePath());
            inputFileTxt.setText(file.toString());
        }
    }//GEN-LAST:event_openFileBtnMouseClicked

    private void returnBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBtnMouseClicked
        this.dispose();
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        homePage.setLocationRelativeTo(null);
    }//GEN-LAST:event_returnBtnMouseClicked

    private void knnStartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_knnStartBtnMouseClicked

        try {
            model.buildkNN("D:\\Doc\\Projects\\JavaApp\\diemthi_train.arff");
            JOptionPane.showMessageDialog(this, "Thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            Logger.getLogger(KnnFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_knnStartBtnMouseClicked

    private void evaluateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluateBtnMouseClicked
        try {
            
            resultTxt.setText(model.evaluatekNN("D:\\Doc\\Projects\\JavaApp\\diemthi_test.arff"));
        } catch (Exception ex) {
            Logger.getLogger(KnnFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_evaluateBtnMouseClicked

    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        if (inputFileTxt.getText().length()>0){
            try {
                model.predictClassLabel(inputFileTxt.getText(), "D:\\Doc\\Projects\\JavaApp\\diemthi_predict_knn.arff");
                JOptionPane.showMessageDialog(this, "Thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(KnnFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Vui lòng điền dữ liệu trước khi thực hiện!","Thông báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_startBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    KnnFrame knnFrame = new KnnFrame();
                    knnFrame.setVisible(true);
                    knnFrame.setLocationRelativeTo(null);
                    knnFrame.setTitle("Phân lớp dữ liệu");
                } catch (Exception ex) {
                    Logger.getLogger(KnnFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton evaluateBtn;
    private javax.swing.JTextField inputFileTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton knnStartBtn;
    private javax.swing.JTextField knnTxt;
    private javax.swing.JButton openFileBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextArea resultTxt;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
